import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rohit Reddy Gangwar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hi, I&apos;m Rohit. </h1>

        <p className={styles.description}>Full stack developer</p>

        <div className={styles.grid}>
          <a href="https://relay.rohitman47.xyz" className={styles.card}>
            <h2>Relay</h2>
            <p>Free video conferencing</p>
          </a>

          <a href="https://animex9.herokuapp.com" className={styles.card}>
            <h2>Animex</h2>
            <p>Watch HD anime for free </p>
          </a>

          <a href="https://wapweather.netlify.app" className={styles.card}>
            <h2>WAP Weather</h2>
            <p>Weather Info</p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
